name: Deploy Website

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: React basic app Deploying to surge
    steps:
    - uses: actions/checkout@v2
      
    - name: Install NodeJS
      uses: actions/setup-node@v2-beta
      with:
        node-version: 16.17.0
          
          
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install --ignore-engines # will run `yarn install` command   
          
    - name: Build React App
      run: sudo yarn build
     
    - name: Install surge
      run: yarn add --global surge --ignore-engines
     
    - name: Deploy to surge
      run: surge ./build usmanali0011234.surge.sh --token ${{secrets.SURGE_TOKEN}}


